RentalManagement/RentalManagement/Models/MaintainenceRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RentalManagement.Models
{
    public class MaintainenceRequest
    {
        [Key]
        public int Id { get; set; }
        public DateTime TimeAndDateOfRequest { get; set; }
        public string Request { get; set; }
        [ForeignKey("Apartment")]
        public int ApartmentId { get; set; }
        public Apartment Apartment { get; set; }
    }
}

RentalManagement/RentalManagement/Controllers/MaintainenceRequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RentalManagement.Models;
using Microsoft.AspNet.Identity;

namespace RentalManagement.Controllers
{
    public class MaintainenceRequestsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MaintainenceRequests
        public ActionResult Index()
        {
            var maintainenceRequest = db.MaintainenceRequest.Include(m => m.Apartment);
            return View(maintainenceRequest.ToList());
        }

        // GET: MaintainenceRequests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaintainenceRequest maintainenceRequest = db.MaintainenceRequest.Find(id);
            if (maintainenceRequest == null)
            {
                return HttpNotFound();
            }
            return View(maintainenceRequest);
        }

        // GET: MaintainenceRequests/Create
        public ActionResult Create()
        {
            ViewBag.ApartmentId = new SelectList(db.Apartment, "Id", "Features");
            return View();
        }

        // POST: MaintainenceRequests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MaintainenceRequest maintainenceRequest)
        {
            var userId = User.Identity.GetUserId();
            var tenant = db.Tenant.Include(a => a.Apartment).SingleOrDefault(t => t.ApplicationUserId == userId);
            maintainenceRequest.TimeAndDateOfRequest = DateTime.Now;
            maintainenceRequest.ApartmentId = tenant.ApartmentId;
            maintainenceRequest.Apartment = tenant.Apartment;

            if (ModelState.IsValid)
            {
                db.MaintainenceRequest.Add(maintainenceRequest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ApartmentId = new SelectList(db.Apartment, "Id", "Features", maintainenceRequest.ApartmentId);
            return View(maintainenceRequest);
        }

        // GET: MaintainenceRequests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaintainenceRequest maintainenceRequest = db.MaintainenceRequest.Find(id);
            if (maintainenceRequest == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApartmentId = new SelectList(db.Apartment, "Id", "Features", maintainenceRequest.ApartmentId);
            return View(maintainenceRequest);
        }

        // POST: MaintainenceRequests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TimeAndDateOfRequest,ApartmentId")] MaintainenceRequest maintainenceRequest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(maintainenceRequest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApartmentId = new SelectList(db.Apartment, "Id", "Features", maintainenceRequest.ApartmentId);
            return View(maintainenceRequest);
        }

        // GET: MaintainenceRequests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaintainenceRequest maintainenceRequest = db.MaintainenceRequest.Find(id);
            if (maintainenceRequest == null)
            {
                return HttpNotFound();
            }
            return View(maintainenceRequest);
        }

        // POST: MaintainenceRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MaintainenceRequest maintainenceRequest = db.MaintainenceRequest.Find(id);
            db.MaintainenceRequest.Remove(maintainenceRequest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RentalManagement/RentalManagement/Views/MaintainenceRequests/Create.cshtml
@model RentalManagement.Models.MaintainenceRequest

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <br /><br /><br /><br /><br /><br />
<h2>Create</h2>
@using (Html.BeginForm("Create", "MaintainenceRequests"))
{
    @Html.AntiForgeryToken()

    <div class="form-inline">
        <h5>Hello, please enter your maintenance request</h5>
        
        @Html.TextAreaFor(model => model.Request, 5, 120, null)
        <br /><br />
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>


}

</body>


RentalManagement/RentalManagement/Views/MaintainenceRequests/Delete.cshtml
@model RentalManagement.Models.MaintainenceRequest

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MaintainenceRequest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apartment.Features)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apartment.Features)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeAndDateOfRequest)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeAndDateOfRequest)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RentalManagement/RentalManagement/Views/MaintainenceRequests/Details.cshtml
@model RentalManagement.Models.MaintainenceRequest

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MaintainenceRequest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apartment.Features)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apartment.Features)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeAndDateOfRequest)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeAndDateOfRequest)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RentalManagement/RentalManagement/Views/MaintainenceRequests/Edit.cshtml
@model RentalManagement.Models.MaintainenceRequest

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MaintainenceRequest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TimeAndDateOfRequest, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeAndDateOfRequest, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeAndDateOfRequest, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApartmentId, "ApartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RentalManagement/RentalManagement/Views/MaintainenceRequests/Index.cshtml
@model IEnumerable<RentalManagement.Models.MaintainenceRequest>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
    <th>
        @Html.DisplayNameFor(model => model.Request)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.TimeAndDateOfRequest)
    </th>
    <th></th>
</tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Request)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeAndDateOfRequest)
        </td>
    </tr>
}

</table>
</body>